name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Use Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install -g bun && bun install

      - name: Build
        run: bun run build

      - name: Flatten build folder
        run: |
          # rsyncを使ってシンボリックリンクを実体化（--copy-links オプション）
          rsync -a --copy-links build/client/ build/client_clean/
          rm -rf build/client
          mv build/client_clean build/client

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          name: build-client
          path: build/client

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: build-client
